[package]
name = "abstract_struct"
version = "0.1.0"
authors = ["Las <las@protonmail.ch>"]
license = "MPL-2.0"

[dependencies]
matches = {version = "0.1.7", git = "https://github.com/Laaas/rust-std-candidates"}
itertools = "0.7"
smallvec = "0.6"

[lib]
proc-macro = true
