[package]
name = "abstract_struct"
version = "0.1.0"
authors = ["Las <las@protonmail.ch>"]
license = "MPL-2.0"

[dependencies]
syn = "0.14"
quote = "0.6"
proc-macro2 = {version = "*", features = ["nightly"]}

[lib]
proc-macro = true
